DROP TABLE IF EXISTS bj_reviews;
DROP TABLE IF EXISTS breyers_reviews;
DROP TABLE IF EXISTS hd_reviews;
DROP TABLE IF EXISTS talenti_reviews;
DROP TABLE IF EXISTS talenti_products;
DROP TABLE IF EXISTS hd_products;
DROP TABLE IF EXISTS breyers_products;
DROP TABLE IF EXISTS bj_products;
DROP TABLE IF EXISTS bj_photos;